name: MinGW C++ Tests

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure CMake
        run: cmake -S ./tests/module/engine_overheat_protection_Arduino -B ./build/eop -G "MinGW Makefiles"

      - name: Build
        run: cmake --build ./build/eop

      - name: Run test
        run: ./build/eop/engine_overheat_protection_Arduino_assert_based_test.exe